<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<title>Data</title>

<script type="text/javascript">
window.onload = function() {
  var imgs = document.getElementsByTagName('img'), i, img;
  for (i = 0; i < imgs.length; i++) {
    img = imgs[i];
    // center an image if it is the only element of its parent
    if (img.parentElement.childElementCount === 1)
      img.parentElement.style.textAlign = 'center';
  }
};
</script>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: #990073
   }

   pre .number {
     color: #099;
   }

   pre .comment {
     color: #998;
     font-style: italic
   }

   pre .keyword {
     color: #900;
     font-weight: bold
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: #d14;
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>



<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 13px;
}

body {
  max-width: 800px;
  margin: auto;
  padding: 1em;
  line-height: 20px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 {
   font-size:2.2em;
}

h2 {
   font-size:1.8em;
}

h3 {
   font-size:1.4em;
}

h4 {
   font-size:1.0em;
}

h5 {
   font-size:0.9em;
}

h6 {
   font-size:0.8em;
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre, img {
  max-width: 100%;
}
pre {
  overflow-x: auto;
}
pre code {
   display: block; padding: 0.5em;
}

code {
  font-size: 92%;
  border: 1px solid #ccc;
}

code[class] {
  background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * {
      background: transparent !important;
      color: black !important;
      filter:none !important;
      -ms-filter: none !important;
   }

   body {
      font-size:12pt;
      max-width:100%;
   }

   a, a:visited {
      text-decoration: underline;
   }

   hr {
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote {
      padding-right: 1em;
      page-break-inside: avoid;
   }

   tr, img {
      page-break-inside: avoid;
   }

   img {
      max-width: 100% !important;
   }

   @page :left {
      margin: 15mm 20mm 15mm 10mm;
   }

   @page :right {
      margin: 15mm 10mm 15mm 20mm;
   }

   p, h2, h3 {
      orphans: 3; widows: 3;
   }

   h2, h3 {
      page-break-after: avoid;
   }
}
</style>



</head>

<body>
<p>This vignette illustrates the use of the aSPU package with GWAS Summary Statistics. </p>

<h2>Data</h2>

<p>We will consider the analysis of a coronary artery disease (CAD)
data from the CARDIoGRAM and C4D consortium. The data set contains P value
data for coronary artery disease (CAD). This study comprised 63,746
CAD cases and 130,681 controls. We mapped these SNPs to the 9th KEGG
pathway (<a href="http://www.broadinstitute.org/gsea/msigdb/cards/KEGG_STEROID_BIOSYNTHESIS">KEGG_STEROID_BIOSYNTHESIS</a>)
. Let&#39;s load this subset.</p>

<pre><code class="r">library(aSPU)
data(kegg9)
</code></pre>

<p>The 9th Kegg pathway contains 16 genes.</p>

<pre><code class="r">kegg9$gene.info
</code></pre>

<pre><code>##         V4 V1        V2        V3
## 1    SOAT1  1 179261017 179326453
## 2      LSS 21  47606360  47650738
## 3     SQLE  8 126008720 126036525
## 5  CYP51A1  7  91739463  91766059
## 6    DHCR7 11  71143457  71161477
## 7  CYP27B1 12  58154117  58162976
## 8   DHCR24  1  55313300  55354921
## 9  HSD17B7  1 162758496 162784608
## 10   MSMO1  4 166246818 166266225
## 11   FDFT1  8  11658190  11698818
## 12    LIPA 10  90971326  91013660
## 13     CEL  9 135935365 135949248
## 14  TM7SF2 11  64877341  64885707
## 16   SOAT2 12  53495274  53520323
</code></pre>

<p>The <code>PPs</code> is a list object contains the SNP information for each genes.</p>

<pre><code class="r">## SNPs mapped on 3rd and 4th genes of 9th Kegg pathway
kegg9$PPs[3:4]
</code></pre>

<pre><code>## $CYP51A1
##                    V1 V2       V3        V4
## rs7796370   rs7796370  7 91739652 0.9035991
## rs12056285 rs12056285  7 91743745 0.7552544
## rs10953067 rs10953067  7 91746159 0.9138308
## rs6965936   rs6965936  7 91752154 0.2282090
## rs10953068 rs10953068  7 91752687 0.7363687
## rs10488513 rs10488513  7 91752911 0.9015296
## rs10953069 rs10953069  7 91760477 0.9718199
## rs721015     rs721015  7 91763192 0.3465701
## 
## $CYP27B1
##                    V1 V2       V3        V4
## rs7306830   rs7306830 12 58154246 0.8323711
## rs10783975 rs10783975 12 58157977 0.7783928
## rs276054     rs276054 12 58161746 0.9735500
</code></pre>

<p>The <code>Ps</code> object contains p-value information for mapped
SNPs. Total 394SNPs are mapped on 9th kegg pathway.</p>

<pre><code class="r">length(kegg9$Ps)
</code></pre>

<pre><code>## [1] 394
</code></pre>

<pre><code class="r">kegg9$Ps[1:10]
</code></pre>

<pre><code>##  rs2331902 rs10159067  rs3806284  rs3806283  rs6692913  rs1411479 
##  0.2115124  0.9898204  0.9488433  0.4944396  0.5838916  0.4224329 
## rs12752307 rs12036052 rs12134601 rs10159443 
##  0.3675058  0.1982464  0.9293256  0.9375789
</code></pre>

<p>Using plink,
we mapped our SNPs to the reference population ( Hapmap CEU phase 2
). We dropped the SNPs of minor allele frequency (MAF) less then 5
percent. Among 394 SNPs mapped on 9th Kegg pathway,
330 SNPs are mapped on the reference data. P-values of these
SNPs and correlation matirx of SNPs using the reference population,
saved on <code>nP</code> and <code>ldmatrix</code> object.</p>

<pre><code class="r">kegg9$nP[1:10]
</code></pre>

<pre><code>##   rs487230   rs593398  rs6694813   rs550336 rs17111584   rs683880 
##  0.9209627  0.8499274  0.9741802  0.6074471  0.5866373  0.9607142 
##  rs6588545   rs679804   rs555687   rs497159 
##  0.3860578  0.8845177  0.9036468  0.8872636
</code></pre>

<pre><code class="r">kegg9$ldmatrix[1:10,1:10]
</code></pre>

<pre><code>##              rs487230    rs593398   rs6694813   rs550336  rs17111584
## rs487230    1.0000000 -0.19188474  0.72579887  0.8910864  0.45580139
## rs593398   -0.1918847  1.00000000 -0.17488093 -0.1880254 -0.06052275
## rs6694813   0.7257989 -0.17488093  1.00000000  0.8350461 -0.08326255
## rs550336    0.8910864 -0.18802536  0.83504607  1.0000000  0.47874154
## rs17111584  0.4558014 -0.06052275 -0.08326255  0.4787415  1.00000000
## rs683880    0.9742395 -0.17778169  0.74380068  0.8600249  0.37081386
## rs6588545   0.4128228 -0.02037425 -0.07921255  0.4209425  1.00000000
## rs679804    0.7257989 -0.17488093  1.00000000  0.8350461 -0.08326255
## rs555687    1.0000000 -0.18763049  0.73226324  0.8901041  0.45918526
## rs497159    0.7257989 -0.17488093  1.00000000  0.8350461 -0.08326255
##              rs683880   rs6588545    rs679804   rs555687    rs497159
## rs487230    0.9742395  0.41282283  0.72579887  1.0000000  0.72579887
## rs593398   -0.1777817 -0.02037425 -0.17488093 -0.1876305 -0.17488093
## rs6694813   0.7438007 -0.07921255  1.00000000  0.7322632  1.00000000
## rs550336    0.8600249  0.42094247  0.83504607  0.8901041  0.83504607
## rs17111584  0.3708139  1.00000000 -0.08326255  0.4591853 -0.08326255
## rs683880    1.0000000  0.35886033  0.74380068  0.9740010  0.74380068
## rs6588545   0.3588603  1.00000000 -0.07921255  0.4170467 -0.07921255
## rs679804    0.7438007 -0.07921255  1.00000000  0.7322632  1.00000000
## rs555687    0.9740010  0.41704671  0.73226324  1.0000000  0.73226324
## rs497159    0.7438007 -0.07921255  1.00000000  0.7322632  1.00000000
</code></pre>

<p>The <code>snp.info</code> data object have snp information for each mapped
SNPs. The 1st column is rsID, 2nd column is Chr, 3rd column is
location and 4th column is p-value.</p>

<pre><code class="r">kegg9$snp.info[1:10,]
</code></pre>

<pre><code>##                  rsID Chr      Loc      Pval
## rs487230     rs487230   1 55313762 0.9209627
## rs593398     rs593398   1 55314484 0.8499274
## rs6694813   rs6694813   1 55315191 0.9741802
## rs550336     rs550336   1 55318103 0.6074471
## rs17111584 rs17111584   1 55319284 0.5866373
## rs683880     rs683880   1 55319483 0.9607142
## rs6588545   rs6588545   1 55321962 0.3860578
## rs679804     rs679804   1 55325157 0.8845177
## rs555687     rs555687   1 55325692 0.9036468
## rs497159     rs497159   1 55326142 0.8872636
</code></pre>

<h2>Use of aSPUs function</h2>

<p>Using the following code we can use <code>aSPUs()</code> and <code>GATES2()</code> function
to get gene-wise aSPU and GATES p-value for each gene in 9th Kegg pathway.</p>

<pre><code class="r">Gps&lt;-NULL;
gl &lt;- NULL;
for( g in kegg9$gene.info[,1]) {
    snps &lt;-
    which( ( kegg9$snp.info[,2] == kegg9$gene.info[kegg9$gene.info[,1]==g,2]) &amp;
           (kegg9$snp.info[,3] &gt; kegg9$gene.info[kegg9$gene.info[,1] == g, 3])&amp;
           (kegg9$snp.info[,3] &lt; kegg9$gene.info[kegg9$gene.info[,1] == g, 4]))

    newP &lt;- kegg9$nP[snps] ;
    ldsub &lt;- kegg9$ldmatrix[snps, snps];

    if( length(snps) &gt; 1) {
        out &lt;- aSPUs(newP, corSNP=ldsub , pow=c(1,2,4,8, Inf),
                     n.perm=10000, Ps=TRUE)

        o.pvec = order(newP)
        ldmat &lt;- ldsub[o.pvec, o.pvec]
        gatesp &lt;- GATES2(ldmat, sort(newP))[1]
        Gps &lt;- rbind(Gps, c(length(newP),out$pvs, gatesp))
        gl &lt;- c(gl, g)
    } else if (length(snps) == 1) {
        out &lt;- newP
        gatesp &lt;- newP
        Gps &lt;- rbind(Gps, c(length(newP),rep(out,6), gatesp) )
        gl &lt;- c(gl, g)
    }
}
colnames(Gps)[1] &lt;- &quot;nSNP&quot;
rownames(Gps) &lt;- gl
Gps
</code></pre>

<pre><code>##         nSNP     SPUs1     SPUs2     SPUs4     SPUs8   SPUsInf      aSPUs
## SOAT1     63 0.7927000 0.7915000 0.7965000 0.7943000 0.7525000 0.85611439
## SQLE      49 0.6271000 0.6391000 0.6386000 0.6218000 0.5401000 0.63953605
## CYP51A1    8 0.7880000 0.6929000 0.6192000 0.5708000 0.5147000 0.60643936
## CYP27B1    3 0.9622000 0.9542000 0.9490000 0.9453000 0.9439000 0.95320468
## DHCR24    26 0.9273000 0.8758000 0.8189000 0.7799000 0.7304000 0.79922008
## HSD17B7   43 0.6435000 0.7273000 0.7504000 0.6489000 0.5215000 0.65793421
## MSMO1      7 0.0121000 0.0102000 0.0149000 0.0220000 0.0381000 0.01729827
## FDFT1     54 0.3067000 0.2874000 0.2731000 0.2147000 0.1275000 0.17818218
## LIPA      57 0.0000000 0.0000000 0.0000000 0.0000000 0.0004000 0.00009999
## CEL        5 0.1695000 0.1869000 0.2285000 0.2675000 0.3004000 0.23037696
## TM7SF2     1 0.7816163 0.7816163 0.7816163 0.7816163 0.7816163 0.78161630
## SOAT2     14 0.2189000 0.2507000 0.2978000 0.3468000 0.3794000 0.27077292
##                   Pg
## SOAT1   0.3994139131
## SQLE    0.6527898971
## CYP51A1 0.6798247959
## CYP27B1 0.9735500000
## DHCR24  0.9777507000
## HSD17B7 0.6360037948
## MSMO1   0.0228054242
## FDFT1   0.1360214136
## LIPA    0.0001396509
## CEL     0.2953563549
## TM7SF2  0.7816163000
## SOAT2   0.3239918282
</code></pre>

<p>The row of <code>Gps</code> means each gene, 1st column indicate the number of
SNPs for each gene. 2nd to 6th column indicate SPUs p-values for each
power ( 1,2,4,8 and Inf), 7th column indicate aSPUs p-value and 8th
column indicate p-value of GATES method.
We can see that a gene <em>LIPA</em> is very significant.</p>

<pre><code class="r">g = &quot;LIPA&quot;
    snps &lt;-
    which( ( kegg9$snp.info[,2] == kegg9$gene.info[kegg9$gene.info[,1]==g,2]) &amp;
           (kegg9$snp.info[,3] &gt; kegg9$gene.info[kegg9$gene.info[,1] == g, 3])&amp;
           (kegg9$snp.info[,3] &lt; kegg9$gene.info[kegg9$gene.info[,1] == g, 4]))

newP &lt;- kegg9$nP[snps] ;
newP
</code></pre>

<pre><code>## rs10509568 rs10509569 rs12780342  rs7922269  rs6586175 rs12358054 
## 0.00031650 0.09359480 0.04754370 0.00000756 0.00216860 0.13601460 
##  rs1556478 rs12415827  rs2297475  rs2297473  rs2297472  rs2254747 
## 0.01681000 0.14171810 0.07292150 0.01016540 0.00001680 0.41696630 
##  rs2254670  rs2254636  rs2071510  rs2071509 rs11203041 rs11203042 
## 0.00027910 0.46203620 0.00078460 0.00234250 0.00013330 0.00007830 
##  rs1041390  rs7896502  rs1041389   rs885561   rs951647 rs12257915 
## 0.00009400 0.35422370 0.00165870 0.00016280 0.00140590 0.00023720 
##  rs1576818  rs1576817  rs1029074 rs17117789  rs2902563  rs7074555 
## 0.00173150 0.00102450 0.93826590 0.32191190 0.07394800 0.40199450 
## rs11203047  rs3892343 rs12267584  rs1320496  rs1412444 rs12240489 
## 0.16127510 0.68171880 0.05303330 0.00019150 0.00091350 0.36096050 
##  rs2246949  rs2246942  rs2246941 rs10887934  rs3740044  rs2246833 
## 0.00007240 0.00008090 0.00008000 0.74540170 0.02227500 0.00004490 
##  rs2246828   rs928415  rs6586179  rs1051338  rs2250781  rs2250644 
## 0.00018290 0.05361800 0.04649850 0.00019460 0.00025170 0.00004480 
##  rs2902561  rs2243548  rs2243547  rs1332327  rs2183933  rs1332325 
## 0.57388670 0.00011620 0.00002260 0.00015360 0.72022840 0.01776480 
## rs10887936  rs7094601  rs7922193 
## 0.01108720 0.08830380 0.08558400
</code></pre>

<p><em>LIPA</em> have 57 SNPs mapped and we can see that there are
many significant SNPs. It makes sense that SPUs(1) have less p-value
then SPUs(inf) since there are multiple significant SNPs. GATES have
more power when there are small number of significant SNPs in the
Gene (similar to minP test), so aSPUs have less p-value than GATES.</p>

<h2>Use of aSPUsPath function</h2>

<p>We can get p-value for pathways as follows.
Let&#39;s perform pathway based analysis using aSPUsPath, Gates-Simes and
HYST.</p>

<pre><code class="r">out.g &lt;- GatesSimes(pvec = kegg9$nP, ldmatrix = kegg9$ldmatrix,
                    snp.info=kegg9$snp.info, gene.info = kegg9$gene.info)

out.h &lt;- Hyst(pvec = kegg9$nP, ldmatrix = kegg9$ldmatrix,
              snp.info=kegg9$snp.info, gene.info = kegg9$gene.info)

out.a &lt;- aSPUsPath(kegg9$nP, corSNP = kegg9$ldmatrix, pow=c(1,2,4,8, Inf),
                   pow2 = c(1,2,4,8),
                   snp.info=kegg9$snp.info, gene.info = kegg9$gene.info,
                   n.perm=1000, Ps = TRUE)

out.g; out.h; out.a
</code></pre>

<pre><code>## [1] 0.00167581
</code></pre>

<pre><code>## [1] 0.07557735
</code></pre>

<pre><code>##   SPUsPath1,1   SPUsPath2,1   SPUsPath4,1   SPUsPath8,1 SPUsPathInf,1 
##         0.318         0.375         0.465         0.539         0.550 
##   SPUsPath1,2   SPUsPath2,2   SPUsPath4,2   SPUsPath8,2 SPUsPathInf,2 
##         0.079         0.082         0.118         0.169         0.187 
##   SPUsPath1,4   SPUsPath2,4   SPUsPath4,4   SPUsPath8,4 SPUsPathInf,4 
##         0.017         0.013         0.013         0.016         0.015 
##   SPUsPath1,8   SPUsPath2,8   SPUsPath4,8   SPUsPath8,8 SPUsPathInf,8 
##         0.009         0.007         0.002         0.002         0.002 
##     aSPUsPath 
##         0.009
</code></pre>

<p>As we can see from the gene-wise analysis, there is only one very
significant gene <code>LIPA</code>. In this situation Gates-Simes works well and
Gate-Simes p-value is 0.0016758. On the other hand, HYST works well
when there are many significant genes with similar effects.</p>

<p>The aSPUsPath adaptively consider all SPUsPath(i,j). We can see that
the p-value decrease as our 2nd parameter , <code>pow2</code>, increases. It makes
sense because larger <code>pow2</code> is more effective if there are fewer
associated genes.</p>

</body>

</html>
